// General Quiz question bank - the creator answers these about themselves,
// and their friends later have to guess the same answers.
// Hundreds of ready-made questions; a fresh random set is served each time,
// and "Skip" pulls another unused one from this pool.
const GENERAL_QUESTIONS = [
  { q: "What's my favorite type of music?", options: ["Pop", "Rock", "Hip-hop", "Classical"] },
  { q: "How do I like to spend a perfect weekend?", options: ["Netflix at home", "Party with friends", "Outdoor adventure", "Sleeping all day"] },
  { q: "What's my go-to comfort food?", options: ["Pizza", "Ice cream", "Chocolate", "Noodles"] },
  { q: "Which season do I love the most?", options: ["Summer", "Winter", "Spring", "Autumn"] },
  { q: "What's my favorite way to travel?", options: ["Road trip", "Flight", "Train", "Cruise"] },
  { q: "Which drink do I reach for first?", options: ["Coffee", "Tea", "Soda", "Water"] },
  { q: "What's my ideal pet?", options: ["Dog", "Cat", "Bird", "None"] },
  { q: "How would my friends describe me?", options: ["Funny", "Caring", "Adventurous", "Chill"] },
  { q: "What's my favorite movie genre?", options: ["Comedy", "Action", "Romance", "Horror"] },
  { q: "What do I value most in a friend?", options: ["Honesty", "Humor", "Loyalty", "Kindness"] },
  { q: "Which color do I love the most?", options: ["Blue", "Red", "Green", "Pink"] },
  { q: "What's my dream vacation spot?", options: ["Beach", "Mountains", "Big city", "Countryside"] },
  { q: "What's my morning vibe?", options: ["Early bird", "Snooze master", "Slow starter", "Instantly ready"] },
  { q: "Which social setting do I prefer?", options: ["Small gatherings", "Big parties", "One-on-one", "Alone time"] },
  { q: "What's my favorite dessert?", options: ["Cake", "Cookies", "Pastry", "Fruit"] },
  { q: "How do I handle stress?", options: ["Music", "Exercise", "Talking it out", "Sleeping"] },
  { q: "What's my hidden talent?", options: ["Singing", "Cooking", "Drawing", "Making people laugh"] },
  { q: "Which hobby do I enjoy most?", options: ["Reading", "Gaming", "Sports", "Cooking"] },
  { q: "What's my phone mostly used for?", options: ["Social media", "Music", "Texting", "Photos"] },
  { q: "What's my favorite time of day?", options: ["Morning", "Afternoon", "Evening", "Late night"] },
  { q: "Which cuisine could I eat forever?", options: ["Italian", "Indian", "Chinese", "Mexican"] },
  { q: "What's my go-to karaoke choice?", options: ["Love ballad", "Rap", "Rock anthem", "Pop hit"] },
  { q: "What makes me happiest?", options: ["Family", "Friends", "Achievements", "Adventures"] },
  { q: "Which superpower would I pick?", options: ["Flying", "Invisibility", "Time travel", "Reading minds"] },
  { q: "What's my texting style?", options: ["Emojis everywhere", "Short & quick", "Long paragraphs", "Voice notes"] },
  { q: "What's my ideal Friday night?", options: ["Dinner out", "Movie marathon", "Dancing", "Early to bed"] },
  { q: "Which app do I open first each morning?", options: ["Instagram", "WhatsApp", "YouTube", "Email"] },
  { q: "What's my favorite kind of weather?", options: ["Sunny", "Rainy", "Snowy", "Cloudy"] },
  { q: "How do I take my coffee?", options: ["Black", "With milk", "Extra sweet", "I don't drink it"] },
  { q: "What's my dream car?", options: ["Sports car", "SUV", "Vintage classic", "Electric"] },
  { q: "Which snack can't I resist?", options: ["Chips", "Popcorn", "Chocolate", "Nuts"] },
  { q: "What's my favorite school subject (or was)?", options: ["Math", "Science", "Art", "History"] },
  { q: "How do I prefer to celebrate my birthday?", options: ["Big bash", "Small dinner", "Trip away", "Quiet at home"] },
  { q: "What's my go-to emoji?", options: ["Laughing", "Heart", "Thumbs up", "Crying"] },
  { q: "Which streaming genre do I binge?", options: ["Thrillers", "Comedies", "Documentaries", "Reality TV"] },
  { q: "What's my ideal workout?", options: ["Gym", "Running", "Yoga", "None thanks"] },
  { q: "What kind of books do I love?", options: ["Fiction", "Self-help", "Fantasy", "True stories"] },
  { q: "How organized am I?", options: ["Super neat", "Organized chaos", "A bit messy", "Total mess"] },
  { q: "What's my favorite fast food?", options: ["Burgers", "Fried chicken", "Tacos", "Sandwiches"] },
  { q: "Which holiday do I love most?", options: ["New Year", "Christmas", "Birthday", "Summer break"] },
  { q: "What's my spending style?", options: ["Saver", "Spender", "Balanced", "Impulse buyer"] },
  { q: "How do I react to surprises?", options: ["Love them", "Get shy", "Cry happy tears", "Hate them"] },
  { q: "What's my dream job vibe?", options: ["Creative", "Leadership", "Helping people", "Working solo"] },
  { q: "Which decade's style do I love?", options: ["80s", "90s", "2000s", "Modern"] },
  { q: "What's my favorite thing to do on vacation?", options: ["Relax", "Explore", "Eat everything", "Adventure sports"] },
  { q: "How do I like my eggs?", options: ["Scrambled", "Fried", "Boiled", "I skip them"] },
  { q: "What's my ideal Sunday?", options: ["Sleeping in", "Brunch", "Cleaning up", "Family time"] },
  { q: "Which gadget can't I live without?", options: ["Phone", "Laptop", "Headphones", "Smartwatch"] },
  { q: "What's my favorite ice cream flavor?", options: ["Vanilla", "Chocolate", "Strawberry", "Mint"] },
  { q: "How do I make decisions?", options: ["Gut feeling", "Overthink it", "Ask friends", "Make a list"] },
  { q: "What's my party role?", options: ["Life of the party", "The planner", "The observer", "First to leave"] },
  { q: "Which pet name would I pick?", options: ["Buddy", "Luna", "Max", "Coco"] },
  { q: "What's my guilty pleasure?", options: ["Junk food", "Reality shows", "Online shopping", "Sleeping in"] },
  { q: "How far in advance do I plan?", options: ["Months ahead", "A week", "Day of", "I don't plan"] },
  { q: "What's my favorite type of shoe?", options: ["Sneakers", "Boots", "Sandals", "Formal"] },
  { q: "Which drink at a cafe?", options: ["Latte", "Cappuccino", "Iced coffee", "Hot chocolate"] },
  { q: "What's my communication style?", options: ["Call me", "Text me", "Voice notes", "In person"] },
  { q: "How do I unwind after a long day?", options: ["TV", "Bath", "Scroll phone", "Sleep"] },
  { q: "What's my favorite pizza topping?", options: ["Pepperoni", "Cheese only", "Veggies", "Pineapple"] },
  { q: "Which trait annoys me most?", options: ["Rudeness", "Lateness", "Dishonesty", "Arrogance"] },
  { q: "What's my go-to movie snack?", options: ["Popcorn", "Nachos", "Candy", "Soda"] },
  { q: "How adventurous is my palate?", options: ["Try anything", "Somewhat", "Play it safe", "Very picky"] },
  { q: "What's my favorite board/card game?", options: ["Monopoly", "Uno", "Chess", "Cards"] },
  { q: "Which is my dream pet upgrade?", options: ["Puppy", "Kitten", "Fish tank", "Parrot"] },
  { q: "What's my nap style?", options: ["Power nap", "Long nap", "No naps", "Accidental naps"] },
  { q: "How do I feel about mornings?", options: ["Love them", "Tolerate them", "Hate them", "Depends"] },
  { q: "What's my favorite fruit?", options: ["Mango", "Apple", "Banana", "Grapes"] },
  { q: "Which vibe describes my room?", options: ["Cozy", "Minimal", "Colorful", "Cluttered"] },
  { q: "What's my ideal date?", options: ["Dinner", "Movie", "Long walk", "Adventure day"] },
  { q: "How do I handle spicy food?", options: ["Love it hot", "Mild is fine", "No spice", "Depends on mood"] },
  { q: "What's my favorite social media?", options: ["Instagram", "TikTok", "YouTube", "X / Twitter"] },
  { q: "Which describes my humor?", options: ["Sarcastic", "Silly", "Dry", "Punny"] },
  { q: "What's my dream living place?", options: ["City apartment", "Beach house", "Countryside", "Mountain cabin"] },
  { q: "How do I like gifts?", options: ["Thoughtful", "Surprise me", "Practical", "Experiences"] },
  { q: "What's my favorite warm drink?", options: ["Tea", "Coffee", "Hot chocolate", "Warm milk"] },
  { q: "Which sport do I enjoy watching?", options: ["Football", "Cricket", "Basketball", "None"] },
  { q: "What's my texting reply speed?", options: ["Instant", "Within an hour", "Hours later", "Days later"] },
  { q: "How do I like my music volume?", options: ["Loud", "Moderate", "Soft", "Headphones only"] },
  { q: "What's my favorite kind of party?", options: ["House party", "Club night", "Game night", "Dinner party"] },
  { q: "Which describes my fashion?", options: ["Trendy", "Casual", "Classic", "Comfy"] },
  { q: "What's my dream travel companion?", options: ["Best friend", "Partner", "Family", "Solo"] },
  { q: "How do I feel about surprises parties?", options: ["Love them", "Nervous", "Hate them", "Only small ones"] },
  { q: "What's my favorite breakfast?", options: ["Pancakes", "Eggs & toast", "Cereal", "Just coffee"] },
  { q: "Which describes my energy?", options: ["High energy", "Calm", "Depends on caffeine", "Night owl energy"] },
  { q: "What's my dream concert?", options: ["Pop star", "Rock band", "Rapper", "Classical"] },
  { q: "How do I keep in touch?", options: ["Daily texts", "Weekly calls", "Whenever", "Social media"] },
  { q: "What's my favorite chore (least hated)?", options: ["Cooking", "Cleaning", "Laundry", "Dishes"] },
  { q: "Which color phone case?", options: ["Black", "Clear", "Bright color", "Patterned"] },
  { q: "What's my ideal weather day activity?", options: ["Beach", "Hike", "Stay in", "Shopping"] },
  { q: "How do I take feedback?", options: ["Welcome it", "Get defensive", "Overthink it", "Shrug it off"] },
  { q: "What's my favorite dessert flavor?", options: ["Chocolate", "Vanilla", "Caramel", "Fruity"] },
  { q: "Which describes my planning?", options: ["Spontaneous", "Planner", "Go with flow", "Last minute"] },
  { q: "What's my dream skill to learn?", options: ["An instrument", "New language", "Cooking", "Dancing"] },
  { q: "How do I like my weekends?", options: ["Packed with plans", "Totally free", "Mix of both", "Recovery mode"] },
  { q: "What's my favorite drink at a party?", options: ["Soft drink", "Juice", "Water", "Something fancy"] },
  { q: "Which describes my desk/space?", options: ["Tidy", "Creative mess", "Minimal", "Decorated"] },
  { q: "What's my go-to comfort show?", options: ["Sitcom", "Anime", "Reality TV", "Crime drama"] },
  { q: "How do I show I care?", options: ["Words", "Gifts", "Time together", "Helping out"] },
  { q: "What's my favorite kind of vacation food?", options: ["Street food", "Fine dining", "Local classics", "Familiar favorites"] },
  { q: "Which describes my luck?", options: ["Very lucky", "Average", "Unlucky", "Make my own luck"] },
  { q: "What's my ideal night in?", options: ["Movie & snacks", "Gaming", "Reading", "Early sleep"] },
  { q: "How do I feel about crowds?", options: ["Love the buzz", "Tolerate them", "Avoid them", "Depends"] },
  { q: "What's my favorite type of cake?", options: ["Chocolate", "Cheesecake", "Red velvet", "Vanilla"] },
  { q: "Which describes my mornings off?", options: ["Sleep in", "Early walk", "Big breakfast", "Lazy scroll"] },
  { q: "What's my dream weekend trip?", options: ["Beach getaway", "City break", "Nature retreat", "Staycation"] },
  { q: "How do I pick a restaurant?", options: ["Reviews", "Cravings", "Friends decide", "Same favorites"] },
  { q: "What's my favorite way to relax?", options: ["Music", "Nap", "Walk", "Scroll phone"] },
  { q: "Which describes my style icon?", options: ["Classic star", "Trendsetter", "Sporty", "No idea"] },
  { q: "What's my go-to late-night snack?", options: ["Chips", "Ice cream", "Leftovers", "Cereal"] },
  { q: "How do I feel about spontaneous plans?", options: ["Love them", "Need warning", "Depends on mood", "Prefer planned"] },
  { q: "What's my favorite type of flower?", options: ["Roses", "Sunflowers", "Tulips", "Lilies"] },
  { q: "Which describes my dancing?", options: ["Love it", "Only after hype", "Two left feet", "Watch others"] },
  { q: "What's my dream birthday gift?", options: ["Gadget", "Trip", "Something handmade", "Cash"] },
  { q: "How do I like my tea/coffee sweetness?", options: ["No sugar", "A little", "Very sweet", "I don't drink"] },
  { q: "What's my favorite kind of story?", options: ["Happy ending", "Plot twist", "Real life", "Mystery"] },
  { q: "Which describes my phone battery?", options: ["Always charged", "Always low", "Somewhere mid", "Power saver on"] },
  { q: "What's my ideal group size for fun?", options: ["Just us two", "3-4 friends", "Big group", "Solo is fine"] },
  { q: "How do I feel about public speaking?", options: ["Love it", "Nervous but okay", "Dread it", "Avoid at all costs"] },
  { q: "What's my favorite condiment?", options: ["Ketchup", "Mayo", "Hot sauce", "Mustard"] },
  { q: "Which describes my playlist?", options: ["One genre", "Total mix", "Mood based", "Whatever's trending"] },
  { q: "What's my dream way to spend money?", options: ["Travel", "Tech", "Food", "Save it"] },
  { q: "How do I react to horror movies?", options: ["Love the thrill", "Cover my eyes", "Laugh it off", "Hard no"] },
  { q: "What's my favorite kind of shoes to relax in?", options: ["Slippers", "Socks only", "Barefoot", "Sneakers"] },
  { q: "Which describes my cooking?", options: ["Chef level", "Decent", "Basic only", "I order in"] },
  { q: "What's my ideal alarm sound?", options: ["Gentle", "Loud & jarring", "Music", "No alarm"] },
  { q: "How do I feel about long road trips?", options: ["Love them", "Fun in parts", "Get restless", "Rather fly"] },
  { q: "What's my favorite kind of candy?", options: ["Chocolate", "Gummies", "Sour", "Mints"] },
  { q: "Which describes my note-taking?", options: ["Neat & colorful", "Messy scribbles", "Phone notes", "I don't"] },
  { q: "What's my dream superpower for daily life?", options: ["Teleport", "Never tired", "Speak all languages", "Pause time"] },
  { q: "How do I like to receive news?", options: ["Straight up", "Gently", "With details", "Skip the drama"] },
  { q: "What's my favorite kind of app game?", options: ["Puzzles", "Strategy", "Casual", "I don't game"] },
  { q: "Which describes my closet?", options: ["Color coordinated", "Organized enough", "A pile", "Capsule minimal"] },
  { q: "What's my ideal way to learn something?", options: ["Watch videos", "Read", "Hands-on", "Ask someone"] },
  { q: "How do I feel about camping?", options: ["Love it", "Once in a while", "Only glamping", "No thanks"] },
  { q: "What's my favorite kind of weather to sleep in?", options: ["Rainy", "Cool breeze", "Warm & cozy", "Snowy"] },
  { q: "Which describes my group chat role?", options: ["Always active", "Silent reader", "Meme sharer", "Plan maker"] },
  { q: "What's my dream pet if size didn't matter?", options: ["Big dog", "Tiny kitten", "Horse", "Something exotic"] },
  { q: "How do I feel about trying new restaurants?", options: ["Always up for it", "Sometimes", "Prefer favorites", "Very rarely"] },
  { q: "What's my favorite kind of movie ending?", options: ["Happy", "Twist", "Open ended", "Bittersweet"] },
  { q: "Which describes my handwriting?", options: ["Beautiful", "Readable", "Messy", "Even I can't read it"] },
  { q: "What's my go-to way to cheer up?", options: ["Music", "Comfort food", "Friends", "Alone time"] },
  { q: "How do I feel about waking up early on weekends?", options: ["Happily", "If needed", "Reluctantly", "Never"] },
  { q: "What's my favorite kind of gathering?", options: ["Cozy dinner", "Outdoor picnic", "Game night", "Movie night"] },
  { q: "Which describes my travel packing?", options: ["Overpacker", "Just right", "Light traveler", "Last-minute chaos"] },
  { q: "What's my dream way to end the day?", options: ["Stargazing", "Good book", "Favorite show", "Deep sleep"] },
];
