// General Quiz question bank - the creator answers these about themselves,
// and their friends later have to guess the same answers.
const GENERAL_QUESTIONS = [
  { q: "What's my favorite type of music?", options: ["Pop", "Rock", "Hip-hop", "Classical"] },
  { q: "How do I like to spend a perfect weekend?", options: ["Netflix at home", "Party with friends", "Outdoor adventure", "Sleeping all day"] },
  { q: "What's my go-to comfort food?", options: ["Pizza", "Ice cream", "Chocolate", "Noodles"] },
  { q: "Which season do I love the most?", options: ["Summer", "Winter", "Spring", "Autumn"] },
  { q: "What's my favorite way to travel?", options: ["Road trip", "Flight", "Train", "Cruise"] },
  { q: "Which drink do I reach for first?", options: ["Coffee", "Tea", "Soda", "Water"] },
  { q: "What's my ideal pet?", options: ["Dog", "Cat", "Bird", "None"] },
  { q: "How would my friends describe me?", options: ["Funny", "Caring", "Adventurous", "Chill"] },
  { q: "What's my favorite movie genre?", options: ["Comedy", "Action", "Romance", "Horror"] },
  { q: "What do I value most in a friend?", options: ["Honesty", "Humor", "Loyalty", "Kindness"] },
  { q: "Which color do I love the most?", options: ["Blue", "Red", "Green", "Pink"] },
  { q: "What's my dream vacation spot?", options: ["Beach", "Mountains", "Big city", "Countryside"] },
  { q: "What's my morning vibe?", options: ["Early bird", "Snooze master", "Slow starter", "Instantly ready"] },
  { q: "Which social setting do I prefer?", options: ["Small gatherings", "Big parties", "One-on-one", "Alone time"] },
  { q: "What's my favorite dessert?", options: ["Cake", "Cookies", "Pastry", "Fruit"] },
  { q: "How do I handle stress?", options: ["Music", "Exercise", "Talking it out", "Sleeping"] },
  { q: "What's my hidden talent?", options: ["Singing", "Cooking", "Drawing", "Making people laugh"] },
  { q: "Which hobby do I enjoy most?", options: ["Reading", "Gaming", "Sports", "Cooking"] },
  { q: "What's my phone mostly used for?", options: ["Social media", "Music", "Texting", "Photos"] },
  { q: "What's my favorite time of day?", options: ["Morning", "Afternoon", "Evening", "Late night"] },
  { q: "Which cuisine could I eat forever?", options: ["Italian", "Indian", "Chinese", "Mexican"] },
  { q: "What's my go-to karaoke choice?", options: ["Love ballad", "Rap", "Rock anthem", "Pop hit"] },
  { q: "What makes me happiest?", options: ["Family", "Friends", "Achievements", "Adventures"] },
  { q: "Which superpower would I pick?", options: ["Flying", "Invisibility", "Time travel", "Reading minds"] },
  { q: "What's my texting style?", options: ["Emojis everywhere", "Short & quick", "Long paragraphs", "Voice notes"] },
];
